name: Example Using Secrets

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  secrets:
    runs-on: ubuntu-latest
    name: Demo Using Secrets
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Echo Out The Secret
      env:
        bsides_secret: ${{ secrets.shifting-security-left-demo-secret }}
      run: echo "$bsides_secret"
